<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 0.9.4
// Source: CalculateProjectDeadlinesRequest.proto
//   Date: 2014-03-05 19:32:47

namespace SolasMatch\Common\Protobufs\Requests {

  class CalculateProjectDeadlinesRequest extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $class_name = "CalculateProjectDeadlinesRequest";
    
    /**  @var int */
    public $project_id = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'SolasMatch.Common.Protobufs.Requests.CalculateProjectDeadlinesRequest');

      // REQUIRED STRING class_name = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "class_name";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $f->default   = "CalculateProjectDeadlinesRequest";
      $descriptor->addField($f);

      // REQUIRED INT32 project_id = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "project_id";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <class_name> has a value
     *
     * @return boolean
     */
    public function hasClassName(){
      return $this->_has(1);
    }
    
    /**
     * Clear <class_name> value
     *
     * @return \SolasMatch\Common\Protobufs\Requests\CalculateProjectDeadlinesRequest
     */
    public function clearClassName(){
      return $this->_clear(1);
    }
    
    /**
     * Get <class_name> value
     *
     * @return string
     */
    public function getClassName(){
      return $this->_get(1);
    }
    
    /**
     * Set <class_name> value
     *
     * @param string $value
     * @return \SolasMatch\Common\Protobufs\Requests\CalculateProjectDeadlinesRequest
     */
    public function setClassName( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <project_id> has a value
     *
     * @return boolean
     */
    public function hasProjectId(){
      return $this->_has(2);
    }
    
    /**
     * Clear <project_id> value
     *
     * @return \SolasMatch\Common\Protobufs\Requests\CalculateProjectDeadlinesRequest
     */
    public function clearProjectId(){
      return $this->_clear(2);
    }
    
    /**
     * Get <project_id> value
     *
     * @return int
     */
    public function getProjectId(){
      return $this->_get(2);
    }
    
    /**
     * Set <project_id> value
     *
     * @param int $value
     * @return \SolasMatch\Common\Protobufs\Requests\CalculateProjectDeadlinesRequest
     */
    public function setProjectId( $value){
      return $this->_set(2, $value);
    }
  }
}

