<?php
namespace SolasMatch\Common\Protobufs\Requests;

// @@protoc_insertion_point(namespace:.SolasMatch.Common.Protobufs.Requests.UserTaskScoreRequest)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: UserTaskScoreRequest.proto
 *
 * -*- magic methods -*-
 *
 * @method string getClassName()
 * @method void setClassName(\string $value)
 * @method string getTaskId()
 * @method void setTaskId(\string $value)
 */
class UserTaskScoreRequest extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.SolasMatch.Common.Protobufs.Requests.UserTaskScoreRequest)
  
  /**
   * @var string $class_name
   * @tag 1
   * @label required
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $class_name;
  
  /**
   * @var string $task_id
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT32
   **/
  protected $task_id;
  
  
  // @@protoc_insertion_point(properties_scope:.SolasMatch.Common.Protobufs.Requests.UserTaskScoreRequest)

  // @@protoc_insertion_point(class_scope:.SolasMatch.Common.Protobufs.Requests.UserTaskScoreRequest)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "class_name",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => "UserTaskScoreRequest",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT32,
        "name"     => "task_id",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.SolasMatch.Common.Protobufs.Requests.UserTaskScoreRequest)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
