#!/bin/sh

#echo Running $BASH_SOURCE
#set | egrep GIT
#echo PWD is $PWD


FILES_PATTERN='*.sql$|*.php$'
FORBIDDEN='^\+.*\(DROP TABLE\|echo\|xdebug_\|var_dump\|print_r\|(object)\)'
if git diff -U0 `git status -s |grep -v "pre-commit" |cut -b4-`|  grep -i "$FORBIDDEN" -A1 -B2
#if git diff --name-only |     grep -E "$FILES_PATTERN" |  GREP_COLOR='4;5;37;41' xargs grep --color --with-filename -n -i "$FORBIDDEN" 
then 
echo "COMMIT REJECTED Found $FORBIDDEN references. Please remove them before commiting"
 exit 1
fi
exit 0
