<?php

namespace SolasMatch\Common\Lib;

class MemsourceTimezone
{
    public function timezones()
    {
        $timezones = [
            'GHANA' => 'Africa/Accra',
            'ETHIOPIA' => 'Africa/Addis_Ababa',
            'ALGERIA' => 'Africa/Algiers',
            'MALI' => 'Africa/Bamako',
            'CENTRAL AFRICAN REPUBLIC' =>'Africa/Bangui',
            'MALAWI' => 'Africa/Blantyre',
            'CONGO' => 'Africa/Brazzaville',
            'EGYPT' => 'Africa/Cairo',
            'MOROCCO' => 'Africa/Casablanca',
            'SENEGAL' => 'Africa/Dakar',
            'TANZANIA UNITED REPUBLIC OF' => 'Africa/Dar_es_Salaam',
            'SIERRA LEONE' => 'Africa/Freetown',
            'BOTSWANA' => 'Africa/Gaborone',
            'ZIMBABWE' => 'Africa/Harare',
            'SOUTH AFRICA' => 'Africa/Johannesburg',
            'SOUTH SUDAN' => 'Africa/Juba',
            'UGANDA' => 'Africa/Kampala',
            'SUDAN' => 'Africa/Khartoum',
            'CONGO THE DEMOCRATIC REPUBLIC OF THE' => 'Africa/Kinshasa',
            'NIGERIA' => 'Africa/Lagos',
            'GABON' => 'Africa/Libreville',
            'ANGOLA' => 'Africa/Luanda',
            'ZAMBIA' => 'Africa/Lusaka',
            'MOZAMBIQUE' => 'Africa/Maputo',
            'ESWATINI' => 'Africa/Mbabane',
            'SOMALIA' => 'Africa/Mogadishu',
            'KENYA' => 'Africa/Nairobi',
            'CHAD' => 'Africa/Ndjamena',
            'NIGER' => 'Africa/Niamey',
            'TUNISIA' => 'Africa/Tunis',
            'NAMIBIA' => 'Africa/Windhoek',
            'ARGENTINA' => 'America/Argentina/Buenos_Aires',
            'PARAGUAY' => 'America/Asuncion',
            'COLOMBIA' => 'America/Bogota',
            'VENEZUELA BOLIVARIAN REPUBLIC OF' => 'America/Caracas',
            'CUBA' => 'America/Havana',
            'JAMAICA' => 'America/Jamaica',
            'BOLIVIA PLURINATIONAL STATE OF' => 'America/La_Paz',
            'PERU' => 'America/Lima',
            'NICARAGUA' => 'America/Managua',
            'MEXICO' => 'America/Mexico_City',
            'URUGUAY' => 'America/Montevideo',
            'UNITED STATES' => 'America/New_York',
            'HAITI' => 'America/Port-au-Prince',
            'CHILE' => 'America/Santiago',
            'BRAZIL' => 'America/Sao_Paulo',
            'HONDURAS' => 'America/Tegucigalpa',
            'CANADA' => 'America/Toronto',
            'YEMEN' => 'Asia/Aden',
            'JORDAN' => 'Asia/Amman',
            'TURKMENISTAN' => 'Asia/Ashgabat',
            'IRAQ' => 'Asia/Baghdad',
            'AZERBAIJAN' => 'Asia/Baku',
            'THAILAND' => 'Asia/Bangkok',
            'LEBANON' => 'Asia/Beirut',
            'INDIA' => 'Asia/Calcutta',
            'SRI LANKA' => 'Asia/Colombo',
            'SYRIAN ARAB REPUBLIC' => 'Asia/Damascus',
            'BANGLADESH' => 'Asia/Dhaka',
            'TAJIKISTAN' => 'Asia/Dushanbe',
            'VIETNAM' => 'Asia/Ho_Chi_Minh',
            'HONG KONG' => 'Asia/Hong_Kong',
            'INDONESIA' => 'Asia/Jakarta',
            'AFGHANISTAN' => 'Asia/Kabul',
            'PAKISTAN' => 'Asia/Karachi',
            'MALAYSIA' => 'Asia/Kuala_Lumpur',
            'PHILIPPINES' => 'Asia/Manila',
            'CAMBODIA' => 'Asia/Phnom_Penh',
            'MYANMAR' => 'Asia/Rangoon',
            'SAUDI ARABIA' => 'Asia/Riyadh',
            'KOREA REPUBLIC OF' => 'Asia/Seoul',
            'CHINA' => 'Asia/Shanghai',
            'SINGAPORE' => 'Asia/Singapore',
            'TAIWAN' => 'Asia/Taipei',
            'UZBEKISTAN' => 'Asia/Tashkent',
            'IRAN ISLAMIC REPUBLIC OF' => 'Asia/Tehran',
            'ISRAEL' => 'Asia/Tel_Aviv',
            'JAPAN' => 'Asia/Tokyo',
            'MONGOLIA' => 'Asia/Ulaanbaatar',
            'ARMENIA' => 'Asia/Yerevan',
            'AUSTRALIA' => 'Australia/Sydney',
            'NETHERLANDS' => 'Europe/Amsterdam',
            'GREECE' => 'Europe/Athens',
            'SERBIA' => 'Europe/Belgrade',
            'GERMANY' => 'Europe/Berlin',
            'SLOVAKIA' => 'Europe/Bratislava',
            'BELGIUM' => 'Europe/Brussels',
            'ROMANIA' => 'Europe/Bucharest',
            'HUNGARY' => 'Europe/Budapest',
            'DENMARK' => 'Europe/Copenhagen',
            'IRELAND' => 'Europe/Dublin',
            'FINLAND' => 'Europe/Helsinki',
            'TÜRKIYE' => 'Europe/Istanbul',
            'UKRAINE' => 'Europe/Kiev',
            'PORTUGAL' => 'Europe/Lisbon',
            'SLOVENIA' => 'Europe/Ljubljana',
            'UNITED KINGDOM' => 'Europe/London',
            'SPAIN' => 'Europe/Madrid',
            'BELARUS' => 'Europe/Minsk',
            'RUSSIAN FEDERATION' => 'Europe/Moscow',
            'NORWAY' => 'Europe/Oslo',
            'FRANCE' => 'Europe/Paris',
            'CZECH REPUBLIC' => 'Europe/Prague',
            'ITALY' => 'Europe/Rome',
            'BOSNIA AND HERZEGOVINA' => 'Europe/Sarajevo',
            'BULGARIA' => 'Europe/Sofia',
            'SWEDEN' => 'Europe/Stockholm',
            'AUSTRIA' => 'Europe/Vienna',
            'POLAND' => 'Europe/Warsaw',
            'SWITZERLAND' => 'Europe/Zurich',
            'MADAGASCAR' => 'Indian/Antananarivo',
            'NEW ZEALAND' => 'Pacific/Auckland',
            'PAPUA NEW GUINEA' => 'Pacific/Port_Moresby',
        ];
        return $timezones;
    }
}
