<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 0.9.4
// Source: ArchivedTask.proto
//   Date: 2012-11-28 13:39:32

namespace  {

  class ArchivedTask extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $archive_id = null;
    
    /**  @var int */
    public $task_id = null;
    
    /**  @var int */
    public $org_id = null;
    
    /**  @var string */
    public $title = null;
    
    /**  @var int */
    public $word_count = null;
    
    /**  @var int */
    public $source_id = null;
    
    /**  @var int */
    public $target_id = null;
    
    /**  @var string */
    public $created_time = null;
    
    /**  @var string */
    public $archived_time = null;
    
    /**  @var string */
    public $impact = null;
    
    /**  @var string */
    public $reference_page = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, '.ArchivedTask');

      // REQUIRED INT32 archive_id = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "archive_id";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED INT32 task_id = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "task_id";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // OPTIONAL INT32 org_id = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "org_id";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING title = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "title";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL INT32 word_count = 5
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 5;
      $f->name      = "word_count";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL INT32 source_id = 6
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 6;
      $f->name      = "source_id";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL INT32 target_id = 7
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 7;
      $f->name      = "target_id";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING created_time = 8
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 8;
      $f->name      = "created_time";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING archived_time = 9
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 9;
      $f->name      = "archived_time";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING impact = 10
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 10;
      $f->name      = "impact";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING reference_page = 11
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 11;
      $f->name      = "reference_page";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <archive_id> has a value
     *
     * @return boolean
     */
    public function hasArchiveId(){
      return $this->_has(1);
    }
    
    /**
     * Clear <archive_id> value
     *
     * @return \ArchivedTask
     */
    public function clearArchiveId(){
      return $this->_clear(1);
    }
    
    /**
     * Get <archive_id> value
     *
     * @return int
     */
    public function getArchiveId(){
      return $this->_get(1);
    }
    
    /**
     * Set <archive_id> value
     *
     * @param int $value
     * @return \ArchivedTask
     */
    public function setArchiveId( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <task_id> has a value
     *
     * @return boolean
     */
    public function hasTaskId(){
      return $this->_has(2);
    }
    
    /**
     * Clear <task_id> value
     *
     * @return \ArchivedTask
     */
    public function clearTaskId(){
      return $this->_clear(2);
    }
    
    /**
     * Get <task_id> value
     *
     * @return int
     */
    public function getTaskId(){
      return $this->_get(2);
    }
    
    /**
     * Set <task_id> value
     *
     * @param int $value
     * @return \ArchivedTask
     */
    public function setTaskId( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <org_id> has a value
     *
     * @return boolean
     */
    public function hasOrgId(){
      return $this->_has(3);
    }
    
    /**
     * Clear <org_id> value
     *
     * @return \ArchivedTask
     */
    public function clearOrgId(){
      return $this->_clear(3);
    }
    
    /**
     * Get <org_id> value
     *
     * @return int
     */
    public function getOrgId(){
      return $this->_get(3);
    }
    
    /**
     * Set <org_id> value
     *
     * @param int $value
     * @return \ArchivedTask
     */
    public function setOrgId( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <title> has a value
     *
     * @return boolean
     */
    public function hasTitle(){
      return $this->_has(4);
    }
    
    /**
     * Clear <title> value
     *
     * @return \ArchivedTask
     */
    public function clearTitle(){
      return $this->_clear(4);
    }
    
    /**
     * Get <title> value
     *
     * @return string
     */
    public function getTitle(){
      return $this->_get(4);
    }
    
    /**
     * Set <title> value
     *
     * @param string $value
     * @return \ArchivedTask
     */
    public function setTitle( $value){
      return $this->_set(4, $value);
    }
    
    /**
     * Check if <word_count> has a value
     *
     * @return boolean
     */
    public function hasWordCount(){
      return $this->_has(5);
    }
    
    /**
     * Clear <word_count> value
     *
     * @return \ArchivedTask
     */
    public function clearWordCount(){
      return $this->_clear(5);
    }
    
    /**
     * Get <word_count> value
     *
     * @return int
     */
    public function getWordCount(){
      return $this->_get(5);
    }
    
    /**
     * Set <word_count> value
     *
     * @param int $value
     * @return \ArchivedTask
     */
    public function setWordCount( $value){
      return $this->_set(5, $value);
    }
    
    /**
     * Check if <source_id> has a value
     *
     * @return boolean
     */
    public function hasSourceId(){
      return $this->_has(6);
    }
    
    /**
     * Clear <source_id> value
     *
     * @return \ArchivedTask
     */
    public function clearSourceId(){
      return $this->_clear(6);
    }
    
    /**
     * Get <source_id> value
     *
     * @return int
     */
    public function getSourceId(){
      return $this->_get(6);
    }
    
    /**
     * Set <source_id> value
     *
     * @param int $value
     * @return \ArchivedTask
     */
    public function setSourceId( $value){
      return $this->_set(6, $value);
    }
    
    /**
     * Check if <target_id> has a value
     *
     * @return boolean
     */
    public function hasTargetId(){
      return $this->_has(7);
    }
    
    /**
     * Clear <target_id> value
     *
     * @return \ArchivedTask
     */
    public function clearTargetId(){
      return $this->_clear(7);
    }
    
    /**
     * Get <target_id> value
     *
     * @return int
     */
    public function getTargetId(){
      return $this->_get(7);
    }
    
    /**
     * Set <target_id> value
     *
     * @param int $value
     * @return \ArchivedTask
     */
    public function setTargetId( $value){
      return $this->_set(7, $value);
    }
    
    /**
     * Check if <created_time> has a value
     *
     * @return boolean
     */
    public function hasCreatedTime(){
      return $this->_has(8);
    }
    
    /**
     * Clear <created_time> value
     *
     * @return \ArchivedTask
     */
    public function clearCreatedTime(){
      return $this->_clear(8);
    }
    
    /**
     * Get <created_time> value
     *
     * @return string
     */
    public function getCreatedTime(){
      return $this->_get(8);
    }
    
    /**
     * Set <created_time> value
     *
     * @param string $value
     * @return \ArchivedTask
     */
    public function setCreatedTime( $value){
      return $this->_set(8, $value);
    }
    
    /**
     * Check if <archived_time> has a value
     *
     * @return boolean
     */
    public function hasArchivedTime(){
      return $this->_has(9);
    }
    
    /**
     * Clear <archived_time> value
     *
     * @return \ArchivedTask
     */
    public function clearArchivedTime(){
      return $this->_clear(9);
    }
    
    /**
     * Get <archived_time> value
     *
     * @return string
     */
    public function getArchivedTime(){
      return $this->_get(9);
    }
    
    /**
     * Set <archived_time> value
     *
     * @param string $value
     * @return \ArchivedTask
     */
    public function setArchivedTime( $value){
      return $this->_set(9, $value);
    }
    
    /**
     * Check if <impact> has a value
     *
     * @return boolean
     */
    public function hasImpact(){
      return $this->_has(10);
    }
    
    /**
     * Clear <impact> value
     *
     * @return \ArchivedTask
     */
    public function clearImpact(){
      return $this->_clear(10);
    }
    
    /**
     * Get <impact> value
     *
     * @return string
     */
    public function getImpact(){
      return $this->_get(10);
    }
    
    /**
     * Set <impact> value
     *
     * @param string $value
     * @return \ArchivedTask
     */
    public function setImpact( $value){
      return $this->_set(10, $value);
    }
    
    /**
     * Check if <reference_page> has a value
     *
     * @return boolean
     */
    public function hasReferencePage(){
      return $this->_has(11);
    }
    
    /**
     * Clear <reference_page> value
     *
     * @return \ArchivedTask
     */
    public function clearReferencePage(){
      return $this->_clear(11);
    }
    
    /**
     * Get <reference_page> value
     *
     * @return string
     */
    public function getReferencePage(){
      return $this->_get(11);
    }
    
    /**
     * Set <reference_page> value
     *
     * @param string $value
     * @return \ArchivedTask
     */
    public function setReferencePage( $value){
      return $this->_set(11, $value);
    }
  }
}

