<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 0.9.4
// Source: WorkflowGraph.proto
//   Date: 2013-01-30 12:03:30

namespace  {

  class WorkflowGraph extends \DrSlump\Protobuf\Message {

    /**  @var \WorkflowNode[]  */
    public $rootNode = array();
    
    /**  @var \WorkflowNode[]  */
    public $allNodes = array();
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, '.WorkflowGraph');

      // REPEATED MESSAGE rootNode = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "rootNode";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\WorkflowNode';
      $descriptor->addField($f);

      // REPEATED MESSAGE allNodes = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "allNodes";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\WorkflowNode';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <rootNode> has a value
     *
     * @return boolean
     */
    public function hasRootNode(){
      return $this->_has(1);
    }
    
    /**
     * Clear <rootNode> value
     *
     * @return \WorkflowGraph
     */
    public function clearRootNode(){
      return $this->_clear(1);
    }
    
    /**
     * Get <rootNode> value
     *
     * @param int $idx
     * @return \WorkflowNode
     */
    public function getRootNode($idx = NULL){
      return $this->_get(1, $idx);
    }
    
    /**
     * Set <rootNode> value
     *
     * @param \WorkflowNode $value
     * @return \WorkflowGraph
     */
    public function setRootNode(\WorkflowNode $value, $idx = NULL){
      return $this->_set(1, $value, $idx);
    }
    
    /**
     * Get all elements of <rootNode>
     *
     * @return \WorkflowNode[]
     */
    public function getRootNodeList(){
     return $this->_get(1);
    }
    
    /**
     * Add a new element to <rootNode>
     *
     * @param \WorkflowNode $value
     * @return \WorkflowGraph
     */
    public function addRootNode(\WorkflowNode $value){
     return $this->_add(1, $value);
    }
    
    /**
     * Check if <allNodes> has a value
     *
     * @return boolean
     */
    public function hasAllNodes(){
      return $this->_has(2);
    }
    
    /**
     * Clear <allNodes> value
     *
     * @return \WorkflowGraph
     */
    public function clearAllNodes(){
      return $this->_clear(2);
    }
    
    /**
     * Get <allNodes> value
     *
     * @param int $idx
     * @return \WorkflowNode
     */
    public function getAllNodes($idx = NULL){
      return $this->_get(2, $idx);
    }
    
    /**
     * Set <allNodes> value
     *
     * @param \WorkflowNode $value
     * @return \WorkflowGraph
     */
    public function setAllNodes(\WorkflowNode $value, $idx = NULL){
      return $this->_set(2, $value, $idx);
    }
    
    /**
     * Get all elements of <allNodes>
     *
     * @return \WorkflowNode[]
     */
    public function getAllNodesList(){
     return $this->_get(2);
    }
    
    /**
     * Add a new element to <allNodes>
     *
     * @param \WorkflowNode $value
     * @return \WorkflowGraph
     */
    public function addAllNodes(\WorkflowNode $value){
     return $this->_add(2, $value);
    }
  }
}

