// Auto-generated from UserPrivateProfileForm.html.
// DO NOT EDIT.

library UserPrivateProfileForm_html;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;


// Original code
main(){
}
// Additional generated code
void init_autogenerated() {
  var __root = autogenerated.document.body;
  var __t = new autogenerated.Template(__root);
  __t.create();
  __t.insert();
}

//# sourceMappingURL=UserPrivateProfileForm.html.dart.map