<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 0.9.4
// Source: OAuthResponse.proto
//   Date: 2014-03-05 19:32:46

namespace SolasMatch\Common\Protobufs\Models {

  class OAuthResponse extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $token = null;
    
    /**  @var string */
    public $token_type = null;
    
    /**  @var string */
    public $expires = null;
    
    /**  @var string */
    public $expires_in = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'SolasMatch.Common.Protobufs.Models.OAuthResponse');

      // REQUIRED STRING token = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "token";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED STRING token_type = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "token_type";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED STRING expires = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "expires";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED STRING expires_in = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "expires_in";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <token> has a value
     *
     * @return boolean
     */
    public function hasToken(){
      return $this->_has(1);
    }
    
    /**
     * Clear <token> value
     *
     * @return \SolasMatch\Common\Protobufs\Models\OAuthResponse
     */
    public function clearToken(){
      return $this->_clear(1);
    }
    
    /**
     * Get <token> value
     *
     * @return string
     */
    public function getToken(){
      return $this->_get(1);
    }
    
    /**
     * Set <token> value
     *
     * @param string $value
     * @return \SolasMatch\Common\Protobufs\Models\OAuthResponse
     */
    public function setToken( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <token_type> has a value
     *
     * @return boolean
     */
    public function hasTokenType(){
      return $this->_has(2);
    }
    
    /**
     * Clear <token_type> value
     *
     * @return \SolasMatch\Common\Protobufs\Models\OAuthResponse
     */
    public function clearTokenType(){
      return $this->_clear(2);
    }
    
    /**
     * Get <token_type> value
     *
     * @return string
     */
    public function getTokenType(){
      return $this->_get(2);
    }
    
    /**
     * Set <token_type> value
     *
     * @param string $value
     * @return \SolasMatch\Common\Protobufs\Models\OAuthResponse
     */
    public function setTokenType( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <expires> has a value
     *
     * @return boolean
     */
    public function hasExpires(){
      return $this->_has(3);
    }
    
    /**
     * Clear <expires> value
     *
     * @return \SolasMatch\Common\Protobufs\Models\OAuthResponse
     */
    public function clearExpires(){
      return $this->_clear(3);
    }
    
    /**
     * Get <expires> value
     *
     * @return string
     */
    public function getExpires(){
      return $this->_get(3);
    }
    
    /**
     * Set <expires> value
     *
     * @param string $value
     * @return \SolasMatch\Common\Protobufs\Models\OAuthResponse
     */
    public function setExpires( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <expires_in> has a value
     *
     * @return boolean
     */
    public function hasExpiresIn(){
      return $this->_has(4);
    }
    
    /**
     * Clear <expires_in> value
     *
     * @return \SolasMatch\Common\Protobufs\Models\OAuthResponse
     */
    public function clearExpiresIn(){
      return $this->_clear(4);
    }
    
    /**
     * Get <expires_in> value
     *
     * @return string
     */
    public function getExpiresIn(){
      return $this->_get(4);
    }
    
    /**
     * Set <expires_in> value
     *
     * @param string $value
     * @return \SolasMatch\Common\Protobufs\Models\OAuthResponse
     */
    public function setExpiresIn( $value){
      return $this->_set(4, $value);
    }
  }
}

