<?php
namespace SolasMatch\Common\Protobufs\Models;

// @@protoc_insertion_point(namespace:.SolasMatch.Common.Protobufs.Models.OAuthResponse)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: OAuthResponse.proto
 *
 * -*- magic methods -*-
 *
 * @method string getToken()
 * @method void setToken(\string $value)
 * @method string getTokenType()
 * @method void setTokenType(\string $value)
 * @method string getExpires()
 * @method void setExpires(\string $value)
 * @method string getExpiresIn()
 * @method void setExpiresIn(\string $value)
 */
class OAuthResponse extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.SolasMatch.Common.Protobufs.Models.OAuthResponse)
  
  /**
   * @var string $token
   * @tag 1
   * @label required
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $token;
  
  /**
   * @var string $token_type
   * @tag 2
   * @label required
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $token_type;
  
  /**
   * @var string $expires
   * @tag 3
   * @label required
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $expires;
  
  /**
   * @var string $expires_in
   * @tag 4
   * @label required
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $expires_in;
  
  
  // @@protoc_insertion_point(properties_scope:.SolasMatch.Common.Protobufs.Models.OAuthResponse)

  // @@protoc_insertion_point(class_scope:.SolasMatch.Common.Protobufs.Models.OAuthResponse)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "token",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "token_type",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "expires",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "expires_in",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      // @@protoc_insertion_point(builder_scope:.SolasMatch.Common.Protobufs.Models.OAuthResponse)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
