<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 0.9.4
// Source: PasswordReset.proto
//   Date: 2014-03-05 17:53:45

namespace SolasMatch\Common\Protobufs\Models {

  class PasswordReset extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $password = null;
    
    /**  @var string */
    public $key = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'SolasMatch.Common.Protobufs.Models.PasswordReset');

      // REQUIRED STRING password = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "password";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED STRING key = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "key";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <password> has a value
     *
     * @return boolean
     */
    public function hasPassword(){
      return $this->_has(1);
    }
    
    /**
     * Clear <password> value
     *
     * @return \SolasMatch\Common\Protobufs\Models\PasswordReset
     */
    public function clearPassword(){
      return $this->_clear(1);
    }
    
    /**
     * Get <password> value
     *
     * @return string
     */
    public function getPassword(){
      return $this->_get(1);
    }
    
    /**
     * Set <password> value
     *
     * @param string $value
     * @return \SolasMatch\Common\Protobufs\Models\PasswordReset
     */
    public function setPassword( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <key> has a value
     *
     * @return boolean
     */
    public function hasKey(){
      return $this->_has(2);
    }
    
    /**
     * Clear <key> value
     *
     * @return \SolasMatch\Common\Protobufs\Models\PasswordReset
     */
    public function clearKey(){
      return $this->_clear(2);
    }
    
    /**
     * Get <key> value
     *
     * @return string
     */
    public function getKey(){
      return $this->_get(2);
    }
    
    /**
     * Set <key> value
     *
     * @param string $value
     * @return \SolasMatch\Common\Protobufs\Models\PasswordReset
     */
    public function setKey( $value){
      return $this->_set(2, $value);
    }
  }
}

