<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 0.9.4
// Source: UserTaskStreamNotification.proto
//   Date: 2014-03-05 17:53:49

namespace SolasMatch\Common\Protobufs\Models {

  class UserTaskStreamNotification extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $user_id = null;
    
    /**  @var int */
    public $interval = null;
    
    /**  @var string */
    public $last_sent = null;
    
    /**  @var boolean */
    public $strict = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'SolasMatch.Common.Protobufs.Models.UserTaskStreamNotification');

      // OPTIONAL INT32 user_id = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "user_id";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL INT32 interval = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "interval";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING last_sent = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "last_sent";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL BOOL strict = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "strict";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <user_id> has a value
     *
     * @return boolean
     */
    public function hasUserId(){
      return $this->_has(1);
    }
    
    /**
     * Clear <user_id> value
     *
     * @return \SolasMatch\Common\Protobufs\Models\UserTaskStreamNotification
     */
    public function clearUserId(){
      return $this->_clear(1);
    }
    
    /**
     * Get <user_id> value
     *
     * @return int
     */
    public function getUserId(){
      return $this->_get(1);
    }
    
    /**
     * Set <user_id> value
     *
     * @param int $value
     * @return \SolasMatch\Common\Protobufs\Models\UserTaskStreamNotification
     */
    public function setUserId( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <interval> has a value
     *
     * @return boolean
     */
    public function hasInterval(){
      return $this->_has(2);
    }
    
    /**
     * Clear <interval> value
     *
     * @return \SolasMatch\Common\Protobufs\Models\UserTaskStreamNotification
     */
    public function clearInterval(){
      return $this->_clear(2);
    }
    
    /**
     * Get <interval> value
     *
     * @return int
     */
    public function getInterval(){
      return $this->_get(2);
    }
    
    /**
     * Set <interval> value
     *
     * @param int $value
     * @return \SolasMatch\Common\Protobufs\Models\UserTaskStreamNotification
     */
    public function setInterval( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <last_sent> has a value
     *
     * @return boolean
     */
    public function hasLastSent(){
      return $this->_has(3);
    }
    
    /**
     * Clear <last_sent> value
     *
     * @return \SolasMatch\Common\Protobufs\Models\UserTaskStreamNotification
     */
    public function clearLastSent(){
      return $this->_clear(3);
    }
    
    /**
     * Get <last_sent> value
     *
     * @return string
     */
    public function getLastSent(){
      return $this->_get(3);
    }
    
    /**
     * Set <last_sent> value
     *
     * @param string $value
     * @return \SolasMatch\Common\Protobufs\Models\UserTaskStreamNotification
     */
    public function setLastSent( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <strict> has a value
     *
     * @return boolean
     */
    public function hasStrict(){
      return $this->_has(4);
    }
    
    /**
     * Clear <strict> value
     *
     * @return \SolasMatch\Common\Protobufs\Models\UserTaskStreamNotification
     */
    public function clearStrict(){
      return $this->_clear(4);
    }
    
    /**
     * Get <strict> value
     *
     * @return boolean
     */
    public function getStrict(){
      return $this->_get(4);
    }
    
    /**
     * Set <strict> value
     *
     * @param boolean $value
     * @return \SolasMatch\Common\Protobufs\Models\UserTaskStreamNotification
     */
    public function setStrict( $value){
      return $this->_set(4, $value);
    }
  }
}

