<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 0.9.4
// Source: UserTaskScoreRequest.proto
//   Date: 2012-12-12 13:16:46

namespace  {

  class UserTaskScoreRequest extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $task_id = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, '.UserTaskScoreRequest');

      // OPTIONAL INT32 task_id = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "task_id";
      $f->type      = \DrSlump\Protobuf::TYPE_INT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <task_id> has a value
     *
     * @return boolean
     */
    public function hasTaskId(){
      return $this->_has(1);
    }
    
    /**
     * Clear <task_id> value
     *
     * @return \UserTaskScoreRequest
     */
    public function clearTaskId(){
      return $this->_clear(1);
    }
    
    /**
     * Get <task_id> value
     *
     * @return int
     */
    public function getTaskId(){
      return $this->_get(1);
    }
    
    /**
     * Set <task_id> value
     *
     * @param int $value
     * @return \UserTaskScoreRequest
     */
    public function setTaskId( $value){
      return $this->_set(1, $value);
    }
  }
}

