library SolasMatchDart;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/watcher.dart' as watcher;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import '../../compiled/components/UserPrivateProfileForm.dart';
import 'dart:html';
import "package:web_ui/web_ui.dart";
import "../../lib/Settings.dart";
import "../../lib/Localisation.dart";

UserPrivateProfileForm form;

main() 
{
  watcher.useObservers = true;
  Settings settings = new Settings();
  settings.loadConf().then((bool loaded) {
    if (!loaded) {
      print("Failed to load conf file");
    }
    Localisation.loadFile().then((bool success) {
      if (!success) {
        print("Failed to load strings.xml file");
      }
      init();
    });
  });
}

void init()
{
  form = new UserPrivateProfileForm();
  var buttonElement = query("#deleteUserButton");
  buttonElement.onClick.listen((event) => form.deleteUser());
  var __root = autogenerated.document.body;
  var __e0;
  var __t = new autogenerated.Template(__root);
  __e0 = query("#PrivateProfileForm");
  __t.oneWayBind(() => int.parse(__e0.xtag.attributes['user-id']), (e) { if (__e0.xtag.userId != e) __e0.xtag.userId = e; }, false, false);
  form.host = __e0;
  __t.component(form);
  __t.create();
  __t.insert();
}
