library SolasMatchDart;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/watcher.dart' as watcher;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import '../../compiled/components/ClaimedTasksStream.dart';
import 'dart:html';
import "../../lib/Loader.dart";

void main()
{
  watcher.useObservers = true;
  Loader.load().then((bool loaded) {
    if (loaded) {
      init_autogenerated();
    } else {
      print("Failed to load conf file");
    }   
  });
}

void init_autogenerated() {
  var __root = autogenerated.document.body;
  var __e0;
  var __t = new autogenerated.Template(__root);
  __e0 = query("#claimedTasksStream");
  __t.oneWayBind(() => int.parse(__e0.xtag.attributes['user-id']), 
      (e) { if (__e0.xtag.userId != e) __e0.xtag.userId = e; }, false, false);
  __t.oneWayBind(() => int.parse(__e0.xtag.attributes['tasks-per-page']), 
      (e) { if (__e0.xtag.tasksPerPage != e) __e0.xtag.tasksPerPage = e; }, false, false);
  __t.component(new ClaimedTasksStream()..host = __e0);
  __t.create();
  __t.insert();
}
